import "./globals.css";
import type { Metadata } from "next";
import Providers from "./utils/providers.utils";
import MenuBar from "./components/menu/bar/component";
import FooterBar from "./components/footer/component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MenuBar />
          {children}
          <FooterBar />
        </Providers>
      </body>
    </html>
  );
}
